repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyrefly
        name: pyrefly
        entry: uv run pyrefly check
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        args: ["src"]
